remote_theme : xukimseven/HardCandy-Jekyll

# Site settings 配置站点
title: 'Today and So on'
description: 'Becoming what I want'
keywords: '#Study, #Happiness'
url: 'https://IraJane.github.io' # your host


nav: 
  Home: '/index.html'
  Journal: '/study.html' # 공부 메모 테그로 구분하기
  Timeline: '/timeline.html' 
  Self: '/about.html'

  

# 博主
author: true
name: 'By Seo Young'
NickName: 'IraJane'
webtitle: 'Dear Me'
bio: 'Becoming what I want'
about: true
aboutyou: '#Study, #Happiness'
portraits: '/assets/flower.jpg' # your portraits image file path

# SNS
SNS: true
SNS-icon: #['Facebook', 'github', 'Twitter', 'instagram']
  github: 'https://github.com/IraJane'



# 分页
paginate: 2
paginatepath: ['page:num']

# since
footer:
  since: 2020

# Markdown
markdown: kramdown
kramdown:
  input: GFM
# 代码高亮 使用rouge
highlighter: rouge
# 代码高亮主题使用pygments主题: autumn\ default\ emacs\ friendly\ manni\ murphy\ pastie\ perldoc\ tango 任选一个你喜欢的主题名称填在下面的单引号中
pygmentsTheme: 'default'

# 友情链接
friends:
  jekyll: 'https://www.jekyll.com.cn/'

# 评论 最佳体验 在disqus、livere和Gitment之间三选一
# disqus 评论
disqus: true
disqus_url: 'https://irajane.github.io/' # https://abc.disqus.com/embed.js
# 来必力评论
livere: false
livere_uid: 'MTAyMC8zNDI2OS8xMDgwNg==' # MTAyMC8zNDI2OS8xMDgwNg==
# Gitment评论 OAuth Application
Gitment: false
Gitment_owner: ''  # github用户名
Gitment_repo: ''  # github博客存放的仓库名
client_id: ''  # 注册 OAuth Application 后获得的 client_id
client_secret: ''  # 注册 OAuth Application 后获得的 client_secret

# Share : weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
social-share: false
social-share-items: ['facebook', 'google']

# 百度统计 在baidu-url里填写自己相关的url代码
baidu: false
baidu-url: ''
# 谷歌分析 在google-ID里填写自己在谷歌分析获得的追踪ID
google: true
google-ID: ''

# 博客头信息备选颜色（该部分在站点中不充当站点变量，将其写在post的头信息中用来充当页面变量）
color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)
